// Temporary for example demonstration purposes; String Function which displays a list of favorite cars...
// var car;
// myFunction = (val) => "These are my favorite cars: " + val;
// document.getElementById("demo").innerHTML = myFunction("Volvo, Saab, Fiat, Ford");

// Temporary for example demonstration purposes; Function runs internally and populates the demo div with a boolean indicating if any age in ther given list/array is 18 or larger.  Change to 50 to get false.
// var ages = [2, 10, 18, 20, 13, 5, 40, 33, 18, 7];
// checkAge = (age) => age >= 18; // This is itself a function which returns true/false based on the condition provided.
// function myFunction() {
//     document.getElementById("demo").innerHTML = ages.some(checkAge); // This .some function is key for iterating until/if the condition is met within the array.
// }
// myFunction();

// Tic-Tac-Toe Game Logic
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// This variable keeps track of whose turn it is... The active player is always 'X' in the game...
let activePlayer = 'X'; // Current active player ('X' or 'O')
// This array stores an array of moves. We use this to determine win conditions...
let selectedSquares = []; // Array to store selected squares

// This function is for placing an 'X' or 'O' in a square...
function placeXOrO(squareNumber) {
    // This condition ensures a square hasn't been selected already...
    // The .some() method is used to check each element of the selectedSquares array to see if it contains the square number clicked on...
    if (!selectedSquares.some(element => element.includes(squareNumber))) {
        // This variable retrieves the HTML element id that was clicked...
        let select = document.getElementById(squareNumber);
        // This condition checks whose turn it is...
        if (activePlayer === 'X') {
            // If active player is 'X', the x.png is placed in HTML...
            select.style.backgroundImage = 'url("images/TicTacToe_X.png")';
            // Play placeMove.mp3 only for user X moves
            audio('./media/placeMove.mp3');
        } else {
            // If active player is 'O', the o.png is placed in HTML...
            select.style.backgroundImage = 'url("images/TicTacToe_O.png")';
        }
        // squareNumber and activePlayer are concatenated and added to the array...
        selectedSquares.push(squareNumber + activePlayer);
        // This calls a function to check for any win conditions...
        checkWinConditions();

        // This condition is for changing the active player...
        if (activePlayer === 'X') {
            // If active player is 'X', change it to 'O'...
            activePlayer = 'O';
        } else {
            // If active player is 'O', change it to 'X'...
            activePlayer = 'X';
        }
        // This function plays placement sound for all moves (optional, keep or remove if you want only placeMove.mp3 for X)
        // audio('./media/place.mp3');
        // This condition checks to see if it is the computer's turn...
        if (activePlayer === 'O') {
            // This function disables clicking for the computer's turn...
            disableClick();
            // This function waits 1 second before the computer places an image and enables click...
            setTimeout(function () { computersTurn(); }, 1000);
        }
        // Returning true is needed for the computerTurn() function to work...
        return true;
    }
    // If the square is already selected, the function returns false...
    return false;
}

// This function results in the computer selecting a square...
function computersTurn() {
    // This variable stores a random number between 0 and 8...
    let success = false;
    let pickASquare;
    // This condition allows the while loop to keep trying if a square is selected already...
    while (!success) {
        // A random number between 0 and 8 is selected...
        pickASquare = String(Math.floor(Math.random() * 9));
        // If the random number evaluates to true, the square hasn't been selected yet...
        if (placeXOrO(pickASquare)) {
            // This line calls the function...
            placeXOrO(pickASquare);
            // This changes the boolean and ends the loop...
            success = true;
        }
    }
}

// This function checks for win conditions...
function checkWinConditions() {
    // X 0,1,2 condition...
    if (arrayIncludes('0X', '1X', '2X')) { drawWinLine(50, 100, 558, 100); }
    // X 3,4,5 condition...
    else if (arrayIncludes('3X', '4X', '5X')) { drawWinLine(50, 304, 558, 304); }
    // X 6,7,8 condition...
    else if (arrayIncludes('6X', '7X', '8X')) { drawWinLine(50, 508, 558, 508); }
    // X 0,3,6 condition...
    else if (arrayIncludes('0X', '3X', '6X')) { drawWinLine(100, 50, 100, 558); }
    // X 1,4,7 condition...
    else if (arrayIncludes('1X', '4X', '7X')) { drawWinLine(304, 50, 304, 558); }
    // X 2,5,8 condition...
    else if (arrayIncludes('2X', '5X', '8X')) { drawWinLine(508, 50, 508, 558); }
    // X 6,4,2 condition...
    else if (arrayIncludes('6X', '4X', '2X')) { drawWinLine(100, 508, 510, 90); }
    // X 0,4,8 condition...
    else if (arrayIncludes('0X', '4X', '8X')) { drawWinLine(100, 100, 520, 520); }
    // O 0,1,2 condition...
    else if (arrayIncludes('0O', '1O', '2O')) { drawWinLine(50, 100, 558, 100); }
    // O 3,4,5 condition...
    else if (arrayIncludes('3O', '4O', '5O')) { drawWinLine(50, 304, 558, 304); }
    // O 6,7,8 condition...
    else if (arrayIncludes('6O', '7O', '8O')) { drawWinLine(50, 508, 558, 508); }
    // O 0,3,6 condition...
    else if (arrayIncludes('0O', '3O', '6O')) { drawWinLine(100, 50, 100, 558); }
    // O 1,4,7 condition...
    else if (arrayIncludes('1O', '4O', '7O')) { drawWinLine(304, 50, 304, 558); }
    // O 2,5,8 condition...
    else if (arrayIncludes('2O', '5O', '8O')) { drawWinLine(508, 50, 508, 558); }
    // O 6,4,2 condition...
    else if (arrayIncludes('6O', '4O', '2O')) { drawWinLine(100, 508, 510, 90); }
    // O 0,4,8 condition...
    else if (arrayIncludes('0O', '4O', '8O')) { drawWinLine(100, 100, 520, 520); }
    // This condition checks for a tie. If none of the above conditions are met and 9 squares are selected, the code executes...
    else if (selectedSquares.length >= 9) {
        // This function plays the tie game sound...
        audio('./media/tie.mp3');
        // This function sets a 1 second timer before the resetGame is called...
        setTimeout(function () { resetGame(); }, 1000);
    }
    // This function checks if an array includes 3 strings...
    function arrayIncludes(squareA, squareB, squareC) {
        // These 3 variables will be used to check for 3 in a row...
        const a = selectedSquares.includes(squareA);
        const b = selectedSquares.includes(squareB);
        const c = selectedSquares.includes(squareC);
        // If the 3 variables we pass are all included in our array, true is returned and our else if condition executes the drawWinLine function...
        return (a === true && b === true && c === true);
    }
}

// This function makes our body element temporarily unclickable...
function disableClick() {
    // This makes our body unclickable...
    document.body.style.pointerEvents = 'none';
    // This makes our body clickable again after 1 second...
    setTimeout(function () { document.body.style.pointerEvents = 'auto'; }, 1000);
}

// This function takes a string parameter of the path you set earlier for placement sound...
function audio(audioURL) {
    // We create a new audio object and we pass the path as a parameter...
    let audio = new Audio(audioURL);
    // Play method plays the sound...
    audio.play();
}

// This function utilizes HTML canvas to draw win lines...
function drawWinLine(coordX1, coordY1, coordX2, coordY2) {
    // This line accesses our HTML canvas element...
    const canvas = document.getElementById('win-lines');
    // This line gives us access to methods and properties to use on canvas...
    const c = canvas.getContext('2d');
    // This line indicates where the start of a line is...
    let x1 = coordX1,
        y1 = coordY1,
        x2 = coordX2,
        y2 = coordY2,
        x = x1,
        y = y1;
    // This function interacts with the canvas...
    function animateLineDrawing() {
        // This variable creates the loop for when the line is drawn...
        const animationLoop = requestAnimationFrame(animateLineDrawing);
        // This method clears content from the last loop iteration...
        c.clearRect(0, 0, 608, 608);
        // This method starts a new path...
        c.beginPath();
        // This method moves us to a starting point in our line...
        c.moveTo(x1, y1);
        // This method indicates the end point in our line...
        c.lineTo(x, y);
        // This method sets the width of our line...
        c.lineWidth = 10;
        // This method sets the color of our line...
        c.strokeStyle = 'rgba(70, 255, 33, .8)';
        // This method draws everything we laid out above...
        c.stroke();
        // This condition checks if we've reached the endpoint...
        if (x1 <= x2 && y1 <= y2) {
            // This condition adds 10 to the previous end x point...
            if (x < x2) { x += 10; }
            // This condition adds 10 to the previous end y point...
            if (y < y2) { y += 10; }
            // This condition cancels the animation loop if we've reached the endpoint...
            if (x >= x2 && y >= y2) { cancelAnimationFrame(animationLoop); }
        }
        // This condition is similar to the one above... It is for the case where the line is drawn from bottom to top...
        if (x1 <= x2 && y1 >= y2) {
            if (x < x2) { x += 10; }
            if (y > y2) { y -= 10; }
            if (x >= x2 && y <= y2) { cancelAnimationFrame(animationLoop); }
        }
    }
    // This function clears our canvas after our win line is drawn...
    function clear() {
        // This line starts our animation loop...
        const animationLoop = requestAnimationFrame(clear);
        // This line clears the canvas...
        c.clearRect(0, 0, 608, 608);
        // This line stops the animation loop...
        cancelAnimationFrame(animationLoop);
    }
    // This line disallows clicking while the win sound is playing...
    disableClick();
    // This line plays the win sound...
    audio('./media/winGame.mp3');
    // This line calls the main animation loop...
    animateLineDrawing();
    // This line waits 1 second, then clears the canvas, resets the game, and allows clicking again...
    setTimeout(function () { clear(); resetGame(); }, 1000);
}

// This function resets the game in the event of a tie or a win...
function resetGame() {
    // This for loop iterates through each HTML square element...
    for (let i = 0; i < 9; i++) {
        // This variable gets the HTML element i...
        let square = document.getElementById(String(i));
        // This removes our elements backgroundImage...
        square.style.backgroundImage = '';
    }
    // This resets our array so it is empty and we can start over...
    selectedSquares = [];
}

